name: Portfolio Necromancer Agent

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "agent/**"
      - "src/**"

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run agent workflow
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python agent/agent_runner.py
